# Server Port
server.port=8080

# MongoDB Connection (PASTE YOUR STRING FROM STEP 2 HERE)
# Replace <password> with your actual password!
spring.mongodb.uri=mongodb+srv://trafficAdmin:12345687890smarttrafficcluster.74rqrww.mongodb.net/SmartTrafficDB?retryWrites=true&w=majority

# App Name
spring.application.name=SmartTrafficBackend
